#!/bin/sh

. /etc/rc.subr

name="radarr"
rcvar="${name}_enable"
load_rc_config $name

start_cmd="${name}_start"
stop_cmd="${name}_stop"

radarr_start()
{
    /usr/sbin/daemon -f -p /usr/local/radarr/radarr.pid /usr/local/bin/mono --debug /app/Radarr -nobrowser -data=/config
}

radarr_stop()
{
    pid=`cat /usr/local/radarr/radarr.pid` 2> /dev/null
    if [ -n "${pid}" ]; then
        kill -9 ${pid}
        wait_for_pids ${pid}
        echo "Stopped"
    fi
}
run_rc_command "$@"
