#!/bin/sh

. /etc/rc.subr

name="sonarr"
rcvar="${name}_enable"
load_rc_config $name

start_cmd="${name}_start"
stop_cmd="${name}_stop"

sonarr_start()
{
    /usr/sbin/daemon -f -p /usr/local/sonarr/sonarr.pid /usr/local/bin/mono --debug /app/Sonarr.exe -nobrowser -data=/config
}

sonarr_stop()
{
    pid=`cat /usr/local/sonarr/sonarr.pid` 2> /dev/null
    if [ -n "${pid}" ]; then
        kill -9 ${pid}
        wait_for_pids ${pid}
        echo "Stopped"
    fi
}
run_rc_command "$@"
